<a href="https://colab.research.google.com/github/CPerezMartinez/prog/blob/prog/UNO%2BImagine.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas
!python --version
!apt-get install python3.12

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Python 3.11.11
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3.12 is already the newest version (3.12.9-1+jammy1).
0 upgraded, 0 newly installed, 0 to remove and 22 not upgraded.

Temperatura:

In [ ]:
import pandas as pd

df=pd.read_csv("temperatura coso - Full 1 (1).csv")
df

,Segons,Temperatura a-14,Temperatura passadís,Temperatura pati,Temperatura gimnàs,Temperatura a-23
0,1,22.0,22.0,17.0,20.0,20.0
1,2,22.0,22.0,17.0,20.0,20.0
2,3,22.0,22.0,17.0,20.0,20.0
3,4,22.0,22.0,17.0,20.0,20.0
4,5,22.0,22.0,17.0,20.0,20.0
...,...,...,...,...,...,...
175,176,22.0,21.0,17.0,21.0,20.0
176,177,22.0,21.0,17.0,21.0,20.0
177,178,22.0,21.0,17.0,21.0,20.0
178,179,22.0,21.0,17.0,21.0,20.0
179,180,22.0,21.0,17.0,21.0,20.0

In [ ]:
#Màxim i mínim aula a-14
max_u = df['Temperatura a-14'].max()
print("El màxim de tempertura a l'aula a-14 és", max_u, "ºC")
min_u = df['Temperatura a-14'].min()
print("El mínim de tempertura a l'aula a-14 és", min_u, "ºC")

El màxim de tempertura a l'aula a-14 és 22.0 ºC
El mínim de tempertura a l'aula a-14 és 22.0 ºC

In [ ]:
#Màxim i mínim al passadís
max_u = df['Temperatura passadís'].max()
print("El màxim de tempertura al passadís és", max_u, "ºC")
min_u = df['Temperatura passadís'].min()
print("El mínim de tempertura al passaddís és", min_u, "ºC")

El màxim de tempertura al passadís és 22.0 ºC
El mínim de tempertura al passaddís és 21.0 ºC

In [ ]:
#Màxim i mínim al pati
max_u = df['Temperatura pati'].max()
print("El màxim de tempertura al pati és", max_u, "ºC")
min_u = df['Temperatura pati'].min()
print("El mínim de tempertura al pati és", min_u, "ºC")

El màxim de tempertura al pati és 17.0 ºC
El mínim de tempertura al pati és 17.0 ºC

In [ ]:
#Màxim i mínim al gimnàs
max_u = df['Temperatura gimnàs'].max()
print("El màxim de tempertura al gimnàs és", max_u, "ºC")
min_u = df['Temperatura gimnàs'].min()
print("El mínim de tempertura al gimnàs és", min_u, "ºC")

El màxim de tempertura al gimnàs és 21.0 ºC
El mínim de tempertura al gimnàs és 20.0 ºC

In [ ]:
#Màxim i mínim aula a-23
max_u = df['Temperatura a-23'].max()
print("El màxim de tempertura a l'aula a-23 és", max_u, "ºC")
min_u = df['Temperatura a-23'].min()
print("El mínim de tempertura a l'aula a-23 és", min_u, "ºC")

El màxim de tempertura a l'aula a-23 és 20.0 ºC
El mínim de tempertura a l'aula a-23 és 20.0 ºC

In [ ]:
#Mitjana ponderada
suma_u = df["Temperatura a-14"].sum()
promig_u = (suma_u/179)
suma_dos = df["Temperatura passadís"].sum()
promig_dos = (suma_dos/179)
suma_tres = df["Temperatura pati"].sum()
promig_tres = (suma_tres/179)
suma_quatre = df["Temperatura gimnàs"].sum()
promig_quatre = (suma_dos/179)
suma_cinc = df["Temperatura a-23"].sum()
promig_cinc = (suma_tres/179)

suma_total = (int(promig_u+promig_dos+promig_tres+promig_quatre+promig_cinc))
promig = (suma_total/5)
promig_total = (round(promig,2))
print("El promig de la temperatura és", promig_total, "ºC")

El promig de la temperatura és 19.8 ºC

In [ ]:
import pandas as pd

df=pd.read_csv("Humedad coso - Full 1.csv")
df

,Segons,Humitat a-14,Humitat passadís,Humitat pati,Humitat gimnàs,Humitat a-23
0,1,52.0,51.0,55.0,63.0,38.0
1,2,52.0,51.0,55.0,63.0,38.0
2,3,52.0,51.0,55.0,63.0,38.0
3,4,52.0,51.0,55.0,63.0,38.0
4,5,52.0,51.0,55.0,63.0,38.0
...,...,...,...,...,...,...
175,176,52.0,52.0,56.0,64.0,38.0
176,177,52.0,52.0,56.0,64.0,38.0
177,178,52.0,52.0,56.0,64.0,38.0
178,179,52.0,52.0,56.0,64.0,38.0
179,180,52.0,52.0,56.0,64.0,38.0

In [ ]:
#Màxim i mínim aula a-14
max_u = df['Humitat a-14'].max()
print("El màxim de humitat a l'aula a-14 és", max_u, "%")
min_u = df['Humitat a-14'].min()
print("El mínim de humitat a l'aula a-14 és", min_u, "%")

El màxim de humitat a l'aula a-14 és 52.0 %
El mínim de humitat a l'aula a-14 és 52.0 %

In [ ]:
#Màxim i mínim passadís
max_u = df['Humitat passadís'].max()
print("El màxim de humitat al passadís és", max_u, "%")
min_u = df['Humitat passadís'].min()
print("El mínim de humitat al passadís és", min_u, "%")

El màxim de humitat al passadís és 52.0 %
El mínim de humitat al passadís és 51.0 %

In [ ]:
#Màxim i mínim pati
max_u = df['Humitat pati'].max()
print("El màxim de humitat al pati és", max_u, "%")
min_u = df['Humitat pati'].min()
print("El mínim de humitat al pati és", min_u, "%")

El màxim de humitat al pati és 56.0 %
El mínim de humitat al pati és 55.0 %

In [ ]:
#Màxim i mínim aula gimnàs
max_u = df['Humitat gimnàs'].max()
print("El màxim de humitat al gimnàs és", max_u, "%")
min_u = df['Humitat gimnàs'].min()
print("El mínim de humitat al gimnàs és", min_u, "%")

El màxim de humitat al gimnàs és 64.0 %
El mínim de humitat al gimnàs és 63.0 %

In [ ]:
#Màxim i mínim aula a-23
max_u = df['Humitat a-23'].max()
print("El màxim de humitat a l'aula a-23 és", max_u, "%")
min_u = df['Humitat a-23'].min()
print("El mínim de humitat a l'aula a-23 és", min_u, "%")

El màxim de humitat a l'aula a-23 és 38.0 %
El mínim de humitat a l'aula a-23 és 37.0 %

In [ ]:
#Mitjana ponderada
suma_u = df["Humitat a-14"].sum()
promig_u = (suma_u/179)
suma_dos = df["Humitat passadís"].sum()
promig_dos = (suma_dos/179)
suma_tres = df["Humitat pati"].sum()
promig_tres = (suma_tres/179)
suma_quatre = df["Humitat gimnàs"].sum()
promig_quatre = (suma_dos/179)
suma_cinc = df["Humitat a-23"].sum()
promig_cinc = (suma_tres/179)

suma_total = (int(promig_u+promig_dos+promig_tres+promig_quatre+promig_cinc))
promig = (suma_total/5)
promig_total = (round(promig,2))
print("El promig de la humitat és", promig_total, "%")

El promig de la humitat és 53.4 %